categories:
    - title: 🚀 Features
      label: feat
    - title: 🐛 Bug Fixes
      label: fix
    - title: 🔧 Maintenance
      label: chore
    - title: ⛳️Build
      label: build
template: |
    ## Changes
    $CHANGES
